/* SignalPilot client engine */
const I18N={en:{badge:"Software · Opportunity intelligence",title:"SignalPilot",lead:"Discover companies that are likely to need your service, understand the evidence, prioritize the best accounts, generate compliant outreach, and track the next action — without another heavy CRM.",cta_open:"Open SignalPilot →",cta_demo:"Try demo (no URL needed)",cta_back:"Back to tools",f1t:"Score",f1d:"Fit, Need, Timing, Reachability, Evidence — transparent weights.",f2t:"Evidence",f2d:"Every claim labeled Known, Inferred, or Unknown with a source hint.",f3t:"Outreach",f3d:"Email, LinkedIn, WhatsApp drafts — EN & AR. Never auto-send.",app_title:"Analyze opportunity",app_hint:"Paste a public company website, or use Demo.",lbl_url:"Company website URL",lbl_service:"Your service (optional)",lbl_profile:"Service profile",lbl_msg_lang:"Outreach language",btn_scan:"Analyze URL",btn_demo:"Load demo company",btn_clear:"Clear",insights_h:"Insights",outreach_h:"Outreach draft",btn_copy:"Copy message",btn_pipe:"+ Pipeline",btn_json:"Export JSON",btn_csv:"Export CSV",disc_outreach:"You are responsible for sending. SignalPilot does not auto-send.",pipe_title:"Pipeline",pipe_hint:"Stored in your browser only (localStorage).",btn_clear_pipe:"Clear pipeline",price_title:"Pricing",price_note:"Billing not wired — contact for early access.",cta_access:"Request early access"},ar:{badge:"برمجيات · استخبارات الفرص",title:"SignalPilot",lead:"اكتشف الشركات التي يُحتمل أن تحتاج خدمتك، وافهم الأدلة، رتّب أفضل الحسابات، أنشئ تواصلاً متوافقاً، وتتبع الخطوة التالية.",cta_open:"افتح SignalPilot ←",cta_demo:"جرّب العرض التوضيحي",cta_back:"العودة للأدوات",f1t:"التقييم",f1d:"الملاءمة، الحاجة، التوقيت، إمكانية الوصول، الأدلة.",f2t:"الأدلة",f2d:"كل ادعاء مصنّف معروف / مستنتج / غير معروف.",f3t:"التواصل",f3d:"مسودات بريد ولينكدإن وواتساب — عربي وإنجليزي.",app_title:"تحليل الفرصة",app_hint:"الصق موقع شركة عام، أو استخدم العرض التوضيحي.",lbl_url:"رابط موقع الشركة",lbl_service:"خدمتك (اختياري)",lbl_profile:"ملف الخدمة",lbl_msg_lang:"لغة الرسالة",btn_scan:"تحليل الرابط",btn_demo:"تحميل شركة تجريبية",btn_clear:"مسح",insights_h:"الرؤى",outreach_h:"مسودة التواصل",btn_copy:"نسخ الرسالة",btn_pipe:"+ خط الأنابيب",btn_json:"تصدير JSON",btn_csv:"تصدير CSV",disc_outreach:"أنت مسؤول عن الإرسال.",pipe_title:"خط الأنابيب",pipe_hint:"يُحفظ في متصفحك فقط.",btn_clear_pipe:"مسح الخط",price_title:"الأسعار",price_note:"الفوترة غير مفعّلة.",cta_access:"طلب وصول مبكر"}};
let uiLang="en";
function toggleLang(){uiLang=uiLang==="en"?"ar":"en";document.getElementById("htmlRoot").lang=uiLang;document.getElementById("htmlRoot").dir=uiLang==="ar"?"rtl":"ltr";document.getElementById("langBtn").textContent=uiLang==="en"?"AR":"EN";const t=I18N[uiLang];document.querySelectorAll("[data-i18n]").forEach(el=>{const k=el.getAttribute("data-i18n");if(t[k])el.textContent=t[k];});}
const DEMO={company:"Northwind Digital Studio",domain:"northwind-demo.example",url:"https://northwind-demo.example",summary:"Boutique digital agency. Careers open; blog on redesign; pricing retainers.",signals:{hasCareers:true,hasPricing:true,hasBlog:true,hasContact:true,techHints:["WordPress","HubSpot form"],hiring:true,languages:["en","ar"],sizeHint:"10-40"}};
function clamp(n,a,b){return Math.max(a,Math.min(b,n));}
function scoreFromSignals(sig,profile,serviceText){let fit=40,need=35,timing=40,reach=45,evid=40;if(sig.hasPricing){fit+=15;need+=10;evid+=10;}if(sig.hasCareers||sig.hiring){need+=15;timing+=20;evid+=8;}if(sig.hasBlog){fit+=8;evid+=6;}if(sig.hasContact){reach+=25;evid+=5;}if(sig.techHints&&sig.techHints.length){fit+=10;evid+=8;}if(sig.languages&&sig.languages.includes("ar"))fit+=5;if(profile==="agency"&&(sig.techHints||[]).some(t=>/WordPress|Shopify|Webflow/i.test(t)))fit+=10;if(profile==="ops"&&/book|account|finance|invoic/i.test(serviceText||""))need+=8;if(profile==="saas")fit+=5;fit=clamp(fit,0,100);need=clamp(need,0,100);timing=clamp(timing,0,100);reach=clamp(reach,0,100);evid=clamp(evid,0,100);const total=Math.round(fit*0.25+need*0.25+timing*0.20+reach*0.15+evid*0.15);return{total,fit,need,timing,reach,evid};}
function buildInsights(sig,score){const list=[];if(sig.hasCareers||sig.hiring)list.push({kind:"known",text:"Careers / hiring signal present — team growth may create demand for external services.",source:"Careers or jobs page"});else list.push({kind:"unknown",text:"No clear hiring page detected in this pass.",source:"—"});if(sig.hasPricing)list.push({kind:"known",text:"Public pricing or packages page found — commercial maturity signal.",source:"Pricing page"});else list.push({kind:"inferred",text:"No pricing page found; may still sell via consultative process.",source:"Heuristic"});if(sig.hasBlog)list.push({kind:"inferred",text:"Active content (blog) suggests ongoing marketing investment.",source:"Blog links"});if(sig.hasContact)list.push({kind:"known",text:"Contact path available (form or email pattern).",source:"Contact page"});else list.push({kind:"unknown",text:"Direct contact path not confirmed.",source:"—"});if(sig.techHints&&sig.techHints.length)list.push({kind:"inferred",text:"Tech hints: "+sig.techHints.join(", ")+".",source:"Public HTML/meta"});if(score.total>=70)list.push({kind:"inferred",text:"Overall opportunity score is high relative to profile weights.",source:"Score model"});else if(score.total<45)list.push({kind:"inferred",text:"Lower score — verify fit manually before outreach.",source:"Score model"});return list;}
function buildOutreach(company,service,channel,lang,score){const svc=service||"our services";const name=company||"there";if(lang==="ar"){if(channel==="linkedin")return "مرحباً فريق "+name+"،\n\nلاحظت إشارات عامة على موقعكم. نساعد الشركات المشابهة في "+svc+".\n\nهل يناسبكم مكالمة قصيرة 15 دقيقة؟\n\n— SignalPilot draft";if(channel==="whatsapp")return "مرحباً، أتواصل بخصوص فرصة محتملة مع "+name+". نقدم "+svc+". هل لديكم دقيقة؟\n(مسودة SignalPilot)";return "الموضوع: فكرة سريعة لـ "+name+"\n\nمرحباً،\n\nراجعت الموقع العام لـ "+name+" ووجدت إشارات قد تتوافق مع "+svc+" (درجة: "+score.total+"/100).\n\nأقترح مكالمة تعريفية قصيرة.\n\n---\nمسودة SignalPilot. راجع قبل الإرسال.";}if(lang==="fr"){return channel==="linkedin"?"Bonjour l'équipe "+name+",\n\nSignaux publics sur votre site. Nous aidons avec "+svc+".\n\nÉchange de 15 min ?\n\n— SignalPilot":"Objet: idée pour "+name+"\n\nBonjour,\n\nSignaux alignés avec "+svc+" (score "+score.total+"/100).\n\nAppel exploratoire ?\n\n---\nBrouillon SignalPilot.";}if(channel==="linkedin")return "Hi "+name+" team,\n\nI noticed public signals on your site. We help similar companies with "+svc+".\n\nOpen to a 15-min intro this week?\n\n— SignalPilot draft";if(channel==="whatsapp")return "Hi — possible fit with "+name+". We provide "+svc+". Open to a short chat?\n(SignalPilot draft)";return "Subject: Quick idea for "+name+"\n\nHi,\n\nI reviewed the public site for "+name+" and saw signals that may align with "+svc+" (score: "+score.total+"/100).\n\nHappy to do a short intro call — no obligation.\n\nBest regards\n\n---\nDraft by SignalPilot. Review before sending.";}
function parseHtmlSignals(html){const lower=(html||"").toLowerCase();const sig={hasCareers:/career|jobs|we're hiring|we are hiring|join (our|the) team/.test(lower),hasPricing:/pricing|plans?|packages?|retainer|\/price/.test(lower),hasBlog:/\/blog|articles|insights|resources/.test(lower),hasContact:/contact|get in touch|mailto:|book a call|schedule/.test(lower),techHints:[],hiring:/hiring|we're hiring/.test(lower),languages:[]};if(/wordpress|wp-content/.test(lower))sig.techHints.push("WordPress");if(/shopify/.test(lower))sig.techHints.push("Shopify");if(/hubspot/.test(lower))sig.techHints.push("HubSpot");if(/webflow/.test(lower))sig.techHints.push("Webflow");if(/lang=[\"']ar|dir=[\"']rtl|[\u0600-\u06FF]/.test(html||""))sig.languages.push("ar");sig.languages.push("en");return sig;}
function hostnameFromUrl(u){try{return new URL(u).hostname.replace(/^www\./,"");}catch(e){return u||"company";}}
let currentReport=null;let currentChannel="email";const PIPE_KEY="sp_pipeline_v1";const USAGE_KEY="sp_usage_v1";
function setStatus(type,msg){const el=document.getElementById("statusBox");el.className="status "+type;el.textContent=msg;el.classList.remove("hidden");}
function hideStatus(){document.getElementById("statusBox").classList.add("hidden");}
function escapeHtml(s){return String(s||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;");}
function renderReport(report){currentReport=report;document.getElementById("result").classList.remove("hidden");document.getElementById("companyName").textContent=report.company;document.getElementById("companyMeta").textContent=report.domain+(report.mode?" · "+report.mode:"")+" · score model v1";const s=report.score;document.getElementById("scoreRing").style.setProperty("--p",s.total);document.getElementById("scoreNum").textContent=s.total;document.getElementById("dimBars").innerHTML=[["Fit",s.fit],["Need",s.need],["Timing",s.timing],["Reach",s.reach],["Evidence",s.evid]].map(([n,v])=>"<div class=\"dim\"><strong>"+v+"</strong><span>"+n+"</span></div>").join("");document.getElementById("insightsList").innerHTML=report.insights.map(i=>"<div class=\"insight "+i.kind+"><span class=\"badge-k "+i.kind+"">"+i.kind+"</span>"+escapeHtml(i.text)+" <span style=\"color:var(--muted);font-size:12px\">· "+escapeHtml(i.source||"")+"</span></div>").join("");setChannel(currentChannel);document.getElementById("result").scrollIntoView({behavior:"smooth",block:"start"});}
function setChannel(ch){currentChannel=ch;document.querySelectorAll("#msgTabs .tab").forEach(t=>t.classList.toggle("active",t.dataset.ch===ch));if(!currentReport)return;const lang=document.getElementById("langOut").value;const service=document.getElementById("serviceInput").value;document.getElementById("msgBox").textContent=buildOutreach(currentReport.company,service,ch,lang,currentReport.score);}
function runDemo(){hideStatus();const profile=document.getElementById("profileSelect").value;const service=document.getElementById("serviceInput").value;const score=scoreFromSignals(DEMO.signals,profile,service);const insights=buildInsights(DEMO.signals,score);renderReport({company:DEMO.company,domain:DEMO.domain,url:DEMO.url,mode:"Demo",signals:DEMO.signals,score,insights,summary:DEMO.summary,at:new Date().toISOString()});bumpUsage("demo");}
async function runScan(){const url=(document.getElementById("urlInput").value||"").trim();if(!url){setStatus("error","Enter a URL or click Load demo company.");return;}let parsed;try{parsed=new URL(url.startsWith("http")?url:"https://"+url);}catch(e){setStatus("error","Invalid URL.");return;}if(!/^https?:$/.test(parsed.protocol)){setStatus("error","Only http(s) public URLs.");return;}const host=parsed.hostname;if(/^(localhost|127\.|10\.|192\.168\.|0\.0\.0\.0|::1)/.test(host)){setStatus("error","Private/local hosts are blocked.");return;}setStatus("loading","Analyzing public page…");document.getElementById("scanBtn").disabled=true;const profile=document.getElementById("profileSelect").value;const service=document.getElementById("serviceInput").value;let html="";let mode="Heuristic (client)";try{const res=await fetch("/api/signalpilot/scan",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({url:parsed.href})});if(res.ok){const data=await res.json();if(data.html){html=data.html;mode="Live public scan";}}else{mode="Domain heuristic (fetch unavailable)";}}catch(e){mode="Domain heuristic (offline/CORS)";}const sig=html?parseHtmlSignals(html):{hasCareers:false,hasPricing:false,hasBlog:false,hasContact:true,techHints:[],hiring:false,languages:["en"]};if(!html)sig.hasContact=true;const score=scoreFromSignals(sig,profile,service);const insights=buildInsights(sig,score);const company=hostnameFromUrl(parsed.href);renderReport({company:company.charAt(0).toUpperCase()+company.slice(1),domain:company,url:parsed.href,mode,signals:sig,score,insights,at:new Date().toISOString()});setStatus("loading","Done · "+mode);setTimeout(hideStatus,2500);document.getElementById("scanBtn").disabled=false;bumpUsage("scan");}
function clearResult(){currentReport=null;document.getElementById("result").classList.add("hidden");hideStatus();}
function copyMsg(){const t=document.getElementById("msgBox").textContent;navigator.clipboard.writeText(t).then(()=>setStatus("loading","Copied.")).catch(()=>setStatus("error","Copy failed."));setTimeout(hideStatus,1500);}
function bumpUsage(kind){try{const u=JSON.parse(localStorage.getItem(USAGE_KEY)||"{}");u[kind]=(u[kind]||0)+1;u.last=new Date().toISOString();localStorage.setItem(USAGE_KEY,JSON.stringify(u));}catch(e){}}
function loadPipe(){try{return JSON.parse(localStorage.getItem(PIPE_KEY)||"[]");}catch(e){return[];}}
function savePipe(arr){localStorage.setItem(PIPE_KEY,JSON.stringify(arr));renderPipeline();}
function addToPipeline(){if(!currentReport)return;const arr=loadPipe();if(arr.some(x=>x.domain===currentReport.domain)){setStatus("loading","Already in pipeline.");setTimeout(hideStatus,1500);return;}arr.unshift({id:"sp_"+Date.now(),company:currentReport.company,domain:currentReport.domain,score:currentReport.score.total,status:"New",at:new Date().toISOString()});savePipe(arr);setStatus("loading","Added to pipeline.");setTimeout(hideStatus,1500);}
function setPipeStatus(id,status){const arr=loadPipe().map(x=>x.id===id?{...x,status}:x);savePipe(arr);}
function clearPipeline(){if(!confirm("Clear all pipeline items on this device?"))return;savePipe([]);}
function renderPipeline(){const statuses=["New","Contacted","Replied","Won","Lost"];const arr=loadPipe();const board=document.getElementById("pipelineBoard");board.innerHTML=statuses.map(st=>{const items=arr.filter(x=>x.status===st);return "<div class=\"col\"><h4>"+st+" ("+items.length+")</h4>"+(items.length?items.map(it=>"<div class=\"item\"><strong>"+escapeHtml(it.company)+"</strong><span style=\"color:var(--muted)\">"+it.score+"/100</span><div style=\"margin-top:4px\"><select onchange=\"setPipeStatus('"+it.id+"', this.value)\" style=\"font-size:11px;padding:2px;margin:0;width:100%\">"+statuses.map(s=>"<option value=\""+s+"\" "+(s===it.status?"selected":"")+">"+s+"</option>").join("")+"</select></div></div>").join(""):"<div style=\"font-size:12px;color:var(--muted)\">Empty</div>")+"</div>";}).join("");}
function exportJSON(){if(!currentReport)return;const blob=new Blob([JSON.stringify(currentReport,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="signalpilot-"+(currentReport.domain||"report")+".json";a.click();}
function exportCSV(){if(!currentReport)return;const r=currentReport;const rows=[["company","domain","score","fit","need","timing","reach","evidence","mode","url"],[r.company,r.domain,r.score.total,r.score.fit,r.score.need,r.score.timing,r.score.reach,r.score.evid,r.mode,r.url]];const csv=rows.map(row=>row.map(c=>'"'+String(c).replace(/"/g,'""')+'"').join(",")).join("\n");const blob=new Blob([csv],{type:"text/csv"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="signalpilot-"+(r.domain||"report")+".csv";a.click();}
document.addEventListener("DOMContentLoaded",()=>{renderPipeline();document.getElementById("langOut").addEventListener("change",()=>{if(currentReport)setChannel(currentChannel);});});
